### ISSUE TITLE
 has quit (Excess Flood)

### ISSUE THREAD

**Issue by imhajes** [trackmastersteve/HackServ#25]
-hs[60741]- '.help' (shows this message)
-hs[60741]- '.username' (shows username of machine the bot is running on)
-hs[60741]- '.uptime' (shows bot uptime)
-hs[60741]- '.uname' (get 1-line system info)
-hs[60741]- '.sysinfo' (get formated system info)
* hs[60741] has quit (**Excess Flood**)

**Comment by trackmastersteve** [comment]
That might be an internet connection issue. I have ran quite a few flooding tests on it. I was only able to get it to quit (excess flood) when I was up to about 1,000 bots all running on the same box.
