### ISSUE TITLE
[Help needed?] Adding DoS/DDoS methods

### ISSUE THREAD

**Issue by ghost** [trackmastersteve/HackServ#30]
if you want, i can write a few attack vectors for the bot. Ofcourse without Scapy, which will make the final binary a lot bigger, so the options are a bit limited.

Send me a message if you want me to push a commit :)

**Comment by trackmastersteve** [comment]
@Nexuzzzz  Yes, I'm interested in how this works. If you are going to participate in Hacktoberfest, you can wait until October to push the commit.

**Comment by Nexuzzzz** [comment]
> @Nexuzzzz Yes, I'm interested in how this works. If you are going to participate in Hacktoberfest, you can wait until October to push the commit.

I have never participated in Hacktoberfest, could you elaborate a bit?

**Comment by trackmastersteve** [comment]
It's an event thrown every year by Digital Ocean and Github. basically, they track if you have done a certain number of PRs on Github during the event in October, and you will get some swag (t-shirt and stickers, usually). You can find out more info if you do a search for "Digital Ocean Github Hacktoberfest".

**Comment by Nexuzzzz** [comment]
> It's an event thrown every year by Digital Ocean and Github. basically, they track if you have done a certain number of PRs on Github during the event in October, and you will get some swag (t-shirt and stickers, usually). You can find out more info if you do a search for "Digital Ocean Github Hacktoberfest".

ah, thanks for explaining. I'll just push it later on when i have time (exam year), because i have no idea how to participate or join Hacktoberfest lol

**Comment by trackmastersteve** [comment]
https://hacktoberfest.digitalocean.com/
